export const CHANGE_USERNAME_INPUT = 'CHANGE_USERNAME_INPUT';
export const CHANGE_PASSWORD_INPUT = 'CHANGE_PASSWORD_INPUT';
export const CHANGE_EMAIL_INPUT = 'CHANGE_EMAIL_INPUT';
export const CHANGE_REPEAT_PASSWORD_INPUT = 'CHANGE_REPEAT_PASSWORD_INPUT';
export const DELETE_REPEAT_PASSWORD_INPUT = 'DELETE_REPEAT_PASSWORD_INPUT';
export const DELETE_USERNAME_INPUT = 'DELETE_USERNAME_INPUT';
export const DELETE_PASSWORD_INPUT = 'DELETE_PASSWORD_INPUT';
export const DELETE_EMAIL_INPUT = 'DELETE_EMAIL_INPUT';

export const INIT_USER_STORE = 'INIT_USER_STORE';
export const DELETE_USER_STORE = 'DELETE_USER_STORE';

export const INIT_HOME_STORE = 'INIT_HOME_STORE';

export const SET_BEER_COUNT = 'SET_BEER_COUNT';
export const CLEAR_BEER_COUNT = 'CLEAR_BEER_COUNT';

export const UPDATE_CART_STORE = 'UPDATE_CART_STORE';
export const UPDATE_CART_ITEMS = 'UPDATE_CART_ITEMS';