export const CHANGE_USERNAME_INPUT = 'CHANGE_USERNAME_INPUT';
export const CHANGE_PASSWORD_INPUT = 'CHANGE_PASSWORD_INPUT';
export const CHANGE_EMAIL_INPUT = 'CHANGE_EMAIL_INPUT';
export const CHANGE_REPEAT_PASSWORD_INPUT = 'CHANGE_REPEAT_PASSWORD_INPUT';
export const DELETE_REPEAT_PASSWORD_INPUT = 'DELETE_REPEAT_PASSWORD_INPUT';
export const DELETE_USERNAME_INPUT = 'DELETE_USERNAME_INPUT';
export const DELETE_PASSWORD_INPUT = 'DELETE_PASSWORD_INPUT';
export const DELETE_EMAIL_INPUT = 'DELETE_EMAIL_INPUT';

export const INIT_USER_STORE = 'INIT_USER_STORE';
export const DELETE_USER_STORE = 'DELETE_USER_STORE';
export const UPDATE_IS_ADMIN = 'UPDATE_IS_ADMIN';

export const INIT_HOME_STORE = 'INIT_HOME_STORE';

export const SET_BEER_COUNT = 'SET_BEER_COUNT';
export const CLEAR_BEER_COUNT = 'CLEAR_BEER_COUNT';

export const UPDATE_CART_STORE = 'UPDATE_CART_STORE';
export const UPDATE_CART_ITEMS = 'UPDATE_CART_ITEMS';

export const SET_BEER = 'SET_BEER';
export const SET_BEER_ID = 'SET_BEER_ID';
export const SET_BEER_NAME = 'SET_BEER_NAME';
export const SET_BEER_COUNTRY = 'SET_BEER_COUNTRY';
export const SET_BEER_PRICE = 'SET_BEER_PRICE';
export const SET_BEER_TYPE = 'SET_BEER_TYPE';
export const SET_BEER_DESCRIPTION = 'SET_BEER_DESCRIPTION';
export const SET_BEER_IMG = 'SET_BEER_IMG';

export const SET_FIRST_NAME = 'SET_FIRST_NAME';
export const SET_LAST_NAME = 'SET_LAST_NAME';
export const SET_REASON = 'SET_REASON';
export const DELETE_FIRST_NAME = 'DELETE_FIRST_NAME';
export const DELETE_LAST_NAME = 'DELETE_LAST_NAME';
export const DELETE_REASON = 'DELETE_REASON';